export default {
	"bookSourceGroup": "\u79fb\u52a8",
	"bookSourceName": "\u7b14\u8da3\u9601\u79fb\u52a8\u7248",
	"bookSourceUrl": "https://m.biqugetv.com",
	"enable": true,
	"ruleBookContent": "id.chaptercontent@textNodes",
	"ruleBookLastChapter": "class.directoryArea@tag.p.0@tag.a@textNodes",
	"ruleChapterList": "id.chapterlist@tag.p!0",
	"ruleChapterName": "tag.a@textNodes",
	"ruleChapterUrl": "class.recommend1@tag.h2.1@tag.a@href",
	"ruleContentUrl": "tag.a@href",
	"ruleContentUrlNext": "id.pt_next@href",
	"ruleSearchAuthor": "class.author@textNodes",
	"ruleSearchCoverUrl": "class.lazy@data-original",
	"ruleSearchIntroduce": "class.review@textNodes",
	"ruleSearchList": "class.slide-item index_hot1@class.hot_sale1",
	"ruleSearchName": "class.title@textNodes",
	"ruleSearchNoteUrl": "tag.a@href",
	"ruleSearchUrl": "https://m.biqugetv.com/search.php?keyword=searchKey&t=searchPage",
	"serialNumber": 0,
	"weight": 0
}